# Generated by Django 5.1.4 on 2026-05-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_session_key_alter_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
