# Generated by Django 5.1.4 on 2026-05-12 16:12

from django.db import migrations


def backfill_ownership(apps, schema_editor):
    Highlight = apps.get_model("notes", "Highlight")
    for highlight in Highlight.objects.select_related("article").filter(
        user__isnull=True, session_key__isnull=True
    ):
        highlight.user_id = highlight.article.user_id
        highlight.session_key = highlight.article.session_key
        highlight.save(update_fields=["user_id", "session_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_highlight_ownership'),
    ]

    operations = [
        migrations.RunPython(backfill_ownership, migrations.RunPython.noop),
    ]
